# Generated by Django 4.1.13 on 2023-11-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.CharField(default='98234556677', max_length=20, null=True),
        ),
    ]
